//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrinterHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrinterHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /il.
        /// </summary>
        internal static string AddNewPrinterKey {
            get {
                return ResourceManager.GetString("AddNewPrinterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /dl.
        /// </summary>
        internal static string DeleteSelectedPrinterKey {
            get {
                return ResourceManager.GetString("DeleteSelectedPrinterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TXT Files(*.txt)|*.txt|Office Files|*.doc;*.docx;*.xlsx;*.xls;*.ppt;*.pptx|PDF Files(*.pdf)|*.pdf|Image Files|*.png;*.jpg;*.tiff;*.gif|All Files(*.*)|*.*.
        /// </summary>
        internal static string FileFilterForOpenFileDialog {
            get {
                return ResourceManager.GetString("FileFilterForOpenFileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на !R! CDSK; EXIT;.
        /// </summary>
        internal static string FRPOCheckDisk {
            get {
                return ResourceManager.GetString("FRPOCheckDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на !R! RES; UNIT C;
        ///MCRO DPAT;
        ///NEWP;
        ///SPD .2;
        ///SCP;
        ///SFNT &quot;Helvetica-Nr&quot;, 10;
        ///TEXT &quot;DPAT %1&quot;;
        ///PMRP 1.4, -.1; DPAT %1; PDRP 9, 0;
        ///RPP; PMRP 0, .7;
        ///STRK;
        ///ENDM;
        ///MZP 5, 5;
        ///FONT 13;
        ///CALL DPAT,1;
        ///CALL DPAT,2;
        ///CALL DPAT,3;
        ///CALL DPAT,4;
        ///CALL DPAT,5;
        ///CALL DPAT,6;
        ///CALL DPAT,7;
        ///CALL DPAT,8;
        ///CALL DPAT,9;
        ///CALL DPAT,10;
        ///PAGE;
        ///EXIT;.
        /// </summary>
        internal static string FRPODashedPattern {
            get {
                return ResourceManager.GetString("FRPODashedPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на !R! RES; UNIT C;MAP 5, 8;PAT 52;ARC 1, 2, -45, 45;MAP 5, 10;PIE 2, 0, 10, 20, 30;ARC 0, 2, 0, 60;PAT 20;ARC 0, 2, 60, 180;PAT 10;ARC 0, 2, 180, 360;PAT 1;NEWP;PMZP 4, 2;PARC 4, 3, 1, 90, 270;PARC 5, 4, 1, 180, 360;PARC 6, 3, 1, 270, 90;PARC 5, 2, 1, 0, 180;STRK;MRP 0.6, 1.1;SFNT &quot;Univers-Md&quot;;TEXT &quot;ARC&quot;;PAGE; EXIT;.
        /// </summary>
        internal static string FRPODrawArc {
            get {
                return ResourceManager.GetString("FRPODrawArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на !R! RES; UNIT C; SLS .5;
        ///SPD .01; MAP 10, 1;
        ///CIR .1; MRP 0, .1;
        ///CIR .2; MRP 0, .2;
        ///CIR .4; MRP 0, .4;
        ///CIR .8; MRP 0, .8;
        ///SPD .02;
        ///CIR 1.6; MRP 0, 1.6;
        ///CIR 3.2; MRP 0, 3.2;
        ///SPD .2;
        ///CIR .1; MRP .2, .4;
        ///SFNT &quot;Helvetica-Nr&quot;; TEXT &quot;Cursor now here&quot;;
        ///PAGE;
        ///EXIT;.
        /// </summary>
        internal static string FRPODrawCircle {
            get {
                return ResourceManager.GetString("FRPODrawCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на !R! RES;
        ///UNIT C; SPD .3;
        ///CMNT Cube;
        ///MZP 5, 10;
        ///DRP 4, 0, 2, -2, 0, -4, -4, 0, -2, 2, 0, 4;
        ///MRP 4, 0;
        ///DRP 0, -4, -4, 0, 4, 0, 2, -2;
        ///PAGE;
        ///EXIT;.
        /// </summary>
        internal static string FRPODrawCube {
            get {
                return ResourceManager.GetString("FRPODrawCube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на !R! RES; UNIT C;
        ///MAP 5, 5;
        ///PAT 20;
        ///BOX 4, 1; BLK 4, 1;
        ///MRP 0, 1.5;
        ///BOX 4, 1; BLK 4, 1;
        ///MRP .9, .6;
        ///SFNT &quot;Helvetica-Nr&quot;;
        ///TEXT &quot;OVERPRINTING&quot;;
        ///MRP 0, 5;
        ///PAT 29; BOX 1, -4; BLK 1, -4, H;
        ///PAT 39; BOX 1, -3; BLK 1, -3, H;
        ///PAT 49; BOX 1, -2; BLK 1, -2, H;
        ///PAT 59; BOX 1, -1; BLK 1, -1, H;
        ///PAGE;
        ///EXIT;.
        /// </summary>
        internal static string FRPODrawFilledInBlock {
            get {
                return ResourceManager.GetString("FRPODrawFilledInBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на !R! RES; UNIT C; SIMG 1;
        ///CMNT Drawing clusters;
        ///NEWP;
        ///PMZP 10, 12; PDRP -5.7, -1.75;
        ///PCRP 0, 0, 0, -3.4, 3.1, -3.6; CLSP; PAT 2; FILL;
        ///PMZP 10, 12; PDRP -2.6, -5.35;
        ///PCRP 0, 0, 2.5, -2.5, 4.9, .1; CLSP; PAT 3; FILL;
        ///PMZP 10, 12; PDRP 5.7, -1.75;
        ///PCRP 0, 0, 0, -3.5, -3.4, -3.5; CLSP; PAT 4; FILL;
        ///PMZP 12, 12; PDRP 5.7, -1.75;
        ///PCRP 0, 0, 1.5, 1.75, 0, 3.5; CLSP; PAT 5; FILL;
        ///PMZP 10, 12; PDRP -5.7, 1.75;
        ///PCRP 0, 0, 0, 3.4, 3.1, 3.6; CLSP; PAT 6; FILL;
        ///PMZP 10, 12; PDRP -2.6, 5.35;
        ///PCRP 0, 0, 2.5 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string FRPOFillClosedPath {
            get {
                return ResourceManager.GetString("FRPOFillClosedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на !R! RES; DAM; UNIT C;FSET 1p08V0s0b5T;MCRO PATTERN;FPAT %1, %2, %3, %4, %5, %6, %7, %8;BOX 5, 1; BLK 5, 1; MRP 0, 1.55;TEXT ’FPAT %1, %2, %3, %4, %5, %6, %7, %8;’, L;ENDM;MAP 2, 2; SCP;CALL PATTERN, 3, 3, 0, 0, 0, 0, 0, 0;CALL PATTERN, 255, 0, 0, 0, 0, 0, 0, 0;CALL PATTERN, 1, 1, 1, 1, 1, 1, 1, 255;RPP; MRP 5.5, 0;CALL PATTERN, 0, 0, 24, 60, 60, 24, 0, 0;CALL PATTERN, 1, 2, 4, 8, 16, 32, 64, 128;CALL PATTERN, 8, 8, 8, 8, 8, 8, 8, 8;PAGE;EXIT;.
        /// </summary>
        internal static string FRPOFillPattern {
            get {
                return ResourceManager.GetString("FRPOFillPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на !R! FLST; EXIT;.
        /// </summary>
        internal static string FRPOFontList {
            get {
                return ResourceManager.GetString("FRPOFontList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на !R! FRPO INIT; EXIT;.
        /// </summary>
        internal static string FRPOInit {
            get {
                return ResourceManager.GetString("FRPOInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на !R! MZP 0,0; BOX 30,30; PAGE; EXIT;.
        /// </summary>
        internal static string FRPOMarginTest {
            get {
                return ResourceManager.GetString("FRPOMarginTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на !R! ELOG; EXIT;.
        /// </summary>
        internal static string FRPOPrintEventLog {
            get {
                return ResourceManager.GetString("FRPOPrintEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на !R! STAT; STAT1; EXIT;.
        /// </summary>
        internal static string FRPOPrintStatusPage {
            get {
                return ResourceManager.GetString("FRPOPrintStatusPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на !R! RES; UNIT C; SIMP 3;
        ///MCRO SIMP;
        ///NEWP;
        ///SCOL %2;
        ///PDRP 2, 0, 0, 2, -2, 0, 0, -2;
        ///FILL 1;
        ///PMRP .5, .5;
        ///ENDM;
        ///CALL SIMP,0,0;
        ///CALL SIMP,0,1;
        ///CALL SIMP,0,2;
        ///CALL SIMP,0,3;
        ///CALL SIMP,0,4;
        ///CALL SIMP,0,5;
        ///CALL SIMP,0,6;
        ///CALL SIMP,0,7;
        ///PAGE;
        ///EXIT;.
        /// </summary>
        internal static string FRPOSimpleColorPalette {
            get {
                return ResourceManager.GetString("FRPOSimpleColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /s.
        /// </summary>
        internal static string GetPrintServerProperties {
            get {
                return ResourceManager.GetString("GetPrintServerProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /p.
        /// </summary>
        internal static string GetPropertiesOfSelectedPrinter {
            get {
                return ResourceManager.GetString("GetPropertiesOfSelectedPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon mainicon {
            get {
                object obj = ResourceManager.GetObject("mainicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /o.
        /// </summary>
        internal static string QueueOfSelectedPrinter {
            get {
                return ResourceManager.GetString("QueueOfSelectedPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /c net stop spooler&amp;&amp;DEL /F /S /Q %systemroot%\\System32\\spool\\PRINTERS\\*&amp;&amp;net start spooler&amp;&amp;pause.
        /// </summary>
        internal static string RestartSpooler {
            get {
                return ResourceManager.GetString("RestartSpooler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /k.
        /// </summary>
        internal static string SendDefaultTestPage {
            get {
                return ResourceManager.GetString("SendDefaultTestPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /y.
        /// </summary>
        internal static string SetPrinterAsDefaultKey {
            get {
                return ResourceManager.GetString("SetPrinterAsDefaultKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /c net start spooler&amp;&amp;pause.
        /// </summary>
        internal static string StartSpooler {
            get {
                return ResourceManager.GetString("StartSpooler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /c net stop spooler&amp;&amp;pause.
        /// </summary>
        internal static string StopSpooler {
            get {
                return ResourceManager.GetString("StopSpooler", resourceCulture);
            }
        }
    }
}
